# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [56]:
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [76]:
a=np.random.rand(2,3,5)
a

array([[[0.6797971 , 0.14127673, 0.08529286, 0.04578027, 0.78774412],
        [0.41196135, 0.31727534, 0.32592603, 0.29746103, 0.10073458],
        [0.84064052, 0.34403834, 0.66594126, 0.76362255, 0.65098813]],

       [[0.19670641, 0.39235003, 0.23093183, 0.69186809, 0.17039763],
        [0.96513935, 0.32565602, 0.37586718, 0.91573664, 0.83103348],
        [0.56134545, 0.49875215, 0.83095006, 0.62499418, 0.39277113]]])

In [77]:
# Method 2

In [78]:
# Method 3

#### 4. Print *a*.


In [79]:
# your code here
a

array([[[0.6797971 , 0.14127673, 0.08529286, 0.04578027, 0.78774412],
        [0.41196135, 0.31727534, 0.32592603, 0.29746103, 0.10073458],
        [0.84064052, 0.34403834, 0.66594126, 0.76362255, 0.65098813]],

       [[0.19670641, 0.39235003, 0.23093183, 0.69186809, 0.17039763],
        [0.96513935, 0.32565602, 0.37586718, 0.91573664, 0.83103348],
        [0.56134545, 0.49875215, 0.83095006, 0.62499418, 0.39277113]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [80]:
# your code here

b=np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [81]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [82]:
# your code here
a.size==b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [83]:
# your answer here


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [72]:
#The two arrays can not be summed because they don't have the same shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [84]:
c=b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [85]:
# your code here

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [88]:
# your code/answer here
d=a+c

In [92]:
d.shape
#the summation is possible now beacause a et c has the same dimensions (shape)

(2, 3, 5)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [94]:
# your code/answer here
a,d

(array([[[0.6797971 , 0.14127673, 0.08529286, 0.04578027, 0.78774412],
         [0.41196135, 0.31727534, 0.32592603, 0.29746103, 0.10073458],
         [0.84064052, 0.34403834, 0.66594126, 0.76362255, 0.65098813]],
 
        [[0.19670641, 0.39235003, 0.23093183, 0.69186809, 0.17039763],
         [0.96513935, 0.32565602, 0.37586718, 0.91573664, 0.83103348],
         [0.56134545, 0.49875215, 0.83095006, 0.62499418, 0.39277113]]]),
 array([[[1.6797971 , 1.14127673, 1.08529286, 1.04578027, 1.78774412],
         [1.41196135, 1.31727534, 1.32592603, 1.29746103, 1.10073458],
         [1.84064052, 1.34403834, 1.66594126, 1.76362255, 1.65098813]],
 
        [[1.19670641, 1.39235003, 1.23093183, 1.69186809, 1.17039763],
         [1.96513935, 1.32565602, 1.37586718, 1.91573664, 1.83103348],
         [1.56134545, 1.49875215, 1.83095006, 1.62499418, 1.39277113]]]))

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [97]:
e=np.multiply(a,c)
e

array([[[0.6797971 , 0.14127673, 0.08529286, 0.04578027, 0.78774412],
        [0.41196135, 0.31727534, 0.32592603, 0.29746103, 0.10073458],
        [0.84064052, 0.34403834, 0.66594126, 0.76362255, 0.65098813]],

       [[0.19670641, 0.39235003, 0.23093183, 0.69186809, 0.17039763],
        [0.96513935, 0.32565602, 0.37586718, 0.91573664, 0.83103348],
        [0.56134545, 0.49875215, 0.83095006, 0.62499418, 0.39277113]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [101]:
# your code/answer here
a==e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [107]:
d_max=d.max()
d_max

1.9651393503989194

In [109]:
d_min=d.min()
d_min

1.045780272230035

In [112]:
d_mean=d.mean()
d_mean

1.4820993282199781

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [149]:
f=np.empty((2,3,5), dtype=int)
f

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 35]]])

In [150]:
f=np.append(d, (2,3,5))
f


array([1.6797971 , 1.14127673, 1.08529286, 1.04578027, 1.78774412,
       1.41196135, 1.31727534, 1.32592603, 1.29746103, 1.10073458,
       1.84064052, 1.34403834, 1.66594126, 1.76362255, 1.65098813,
       1.19670641, 1.39235003, 1.23093183, 1.69186809, 1.17039763,
       1.96513935, 1.32565602, 1.37586718, 1.91573664, 1.83103348,
       1.56134545, 1.49875215, 1.83095006, 1.62499418, 1.39277113,
       2.        , 3.        , 5.        ])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
x= [[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

1

6